In [1]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv('C:/Users/rvaib/OneDrive/Desktop/nlp_with_NLTK/nlp/content/spam (1).csv')

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
x_train,  x_test, y_train, y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
x_train.head()

1043            Easy ah?sen got selected means its good..
5561    Get me out of this dump heap. My mom decided t...
1299         Your daily text from me – a favour this time
3374    Looks like you found something to do other tha...
3688               Great! I shoot big loads so get ready!
Name: Message, dtype: object

In [9]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(4457,)
(1115,)
(4457,)
(1115,)


In [10]:
y_train[:4]

1043    0
5561    0
1299    0
3374    0
Name: spam, dtype: int64

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<4457x7761 sparse matrix of type '<class 'numpy.int64'>'
	with 59406 stored elements in Compressed Sparse Row format>

In [13]:
x_train_cv.toarray()
x_train_cv._shape

(4457, 7761)

In [14]:
v.get_feature_names_out()[1600]


'cage'

In [15]:
v.vocabulary_

{'easy': 2519,
 'ah': 870,
 'sen': 6029,
 'got': 3189,
 'selected': 6016,
 'means': 4402,
 'its': 3765,
 'good': 3173,
 'get': 3105,
 'me': 4396,
 'out': 5010,
 'of': 4888,
 'this': 6878,
 'dump': 2490,
 'heap': 3374,
 'my': 4660,
 'mom': 4557,
 'decided': 2206,
 'to': 6955,
 'come': 1904,
 'lowes': 4231,
 'boring': 1439,
 'your': 7727,
 'daily': 2156,
 'text': 6813,
 'from': 3016,
 'favour': 2789,
 'time': 6922,
 'looks': 4189,
 'like': 4104,
 'you': 7723,
 'found': 2958,
 'something': 6327,
 'do': 2378,
 'other': 5001,
 'than': 6825,
 'smoke': 6276,
 'great': 3224,
 'job': 3833,
 'shoot': 6129,
 'big': 1345,
 'loads': 4158,
 'so': 6302,
 'ready': 5614,
 'update_now': 7205,
 'xmas': 7672,
 'offer': 4894,
 'latest': 4022,
 'motorola': 4594,
 'sonyericsson': 6341,
 'nokia': 4804,
 'free': 2977,
 'bluetooth': 1405,
 'double': 2429,
 'mins': 4489,
 '1000': 254,
 'txt': 7114,
 'on': 4934,
 'orange': 4979,
 'call': 1609,
 'mobileupd8': 4542,
 '08000839402': 50,
 'or': 4975,
 'call2optout': 

In [16]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:

np.where(x_train_np[0] != 0)

(array([ 870, 2519, 3173, 3189, 3765, 4402, 6016, 6029], dtype=int64),)

In [18]:
x_train_np[0][4010]

0

In [19]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [20]:
x_test_cv =v.transform(x_test)

In [21]:
y_pred =model.predict(x_test_cv)

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       976
           1       0.97      0.92      0.94       139

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [23]:
for  pred,actual in zip(y_pred,y_test):
    print(f"actual {actual} and prediciton {pred}")



actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and

In [24]:
email =[
    'hey mohan canw e get',
    "free upto 20 percent off"
]
email=v.transform(email)
model.predict(email)

array([0, 1], dtype=int64)

In [29]:
for  pred,actual in zip(y_pred,y_test):
    print(f"actual {actual} and prediciton {pred}")

actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 1 and prediciton 1
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and prediciton 0
actual 0 and

In [26]:
from sklearn.pipeline import Pipeline
clf =Pipeline([
    ('vector',CountVectorizer()),
    ('nb',MultinomialNB())

])

clf.fit(x_train,y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('nb', MultinomialNB())])